#pragma config(Sensor, dgtl2,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mobileLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mobileRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          clawJoint,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void reset()
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
}

void move(const string command, float inches, int power)
{
	reset();
	float tickGoal = 28.64788976 * (inches - 8); //change the (28.647... value)

	if(command == "forward")
	{
		while(SensorValue[leftEncoder] < tickGoal && SensorValue[rightEncoder] < tickGoal)
		{
			motor[frontLeft] = power;
			motor[backLeft] = power;
			motor[frontRight] = power*0.65;
			motor[backRight] = power*0.8;
		}
	}
	else if(command == "backward")
	{
		while(SensorValue[leftEncoder] > tickGoal && SensorValue[rightEncoder] > tickGoal)
		{
			motor[frontLeft] = -power;
			motor[backLeft] = -power;
			motor[frontRight] = -power*0.65;
			motor[backRight] = -power*0.8;
		}
	}

}

void turn(const string command, float degrees, int power)
{
	reset();
	float tickTurn = 28.64788976*3.1415*13 / 360 * degrees; //13 in. distance between left and right wheels

	if(command == "clockwise")
	{
		while(SensorValue[leftEncoder] < tickTurn && SensorValue[rightEncoder] > tickTurn)
		{
			motor[frontRight] = -power;
			motor[backRight] = -power;
			motor[frontLeft] = power;
			motor[backLeft] = power;
		}
	}
	else if(command == "counterclockwise")
	{
		while(SensorValue[leftEncoder] > tickTurn && SensorValue[rightEncoder] < tickTurn)
		{
			motor[frontRight] = power;
			motor[backRight] = power;
			motor[frontLeft] = -power;
			motor[backLeft] = -power;
		}
	}
}
void lift(const string command, float height, int power)
{
    reset();
    //float tickGoal = 98;//vertical inches

    //potentiometer
    if(command == "up")
    {
        motor[armRight] = power;
        motor[armLeft1] = power;
        motor[armLeft2] = power;
    }
    else if(command == "down")
    {
        motor[armRight] = -power;
        motor[armLeft1] = -power;
        motor[armLeft2] = -power;
    }
}

void mobileLift(const string command, int power)
{
    reset();
    int timeGoal = 100;
    if(command == "up")
    {
        wait1Msec(timeGoal);
        motor[mobileLeft] = power;
        motor[mobileRight] = power;
    }
    else if (command == "down")
    {
        wait1Msec(timeGoal);
        motor[mobileLeft] = -power;
        motor[mobileRight] = -power;
    }
}

void claw(const string command, int power)
{
    reset();
    int timeGoal = 100;
    if(command == "open")
    {
        wait1Msec(timeGoal);
        motor[clawJoint] = power;
    }
    else if(command == "close")
    {
        wait1Msec(timeGoal);
        motor[clawJoint] = -power;
    }
}
void go(const string part, const string command, float value, int power)
{
    reset();
    if(part == "move")
    {
        move(command, value, power);
    }
    else if (part == "turn")
    {
        turn(command, value, power);
    }
    else if (part == "lift")
    {
        lift(command, value, power);
    }
    else if (part == "mobileLift")
    {
        mobileLift(command, power);
    }
    else if (part == "claw")
    {
    		claw(command, power);
    }
}

/////////////////////////////////
//             Key             //
/////////////////////////////////
//
// Function: go([part(string)], [command(string)], [value(float)], [power(int)]);
//
// part:
//      move
//          command: forward, backward
//          value:   inches
//      turn
//          command: clockwise, counterclockwise
//          value:   degrees
//      lift
//          command: up, down
//          value:   height
//      mobileLift
//          command: up,down
//          value:   none
//      claw
//          command: open, close
//          value: none
//

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  go("mobileLift", "down", false, 127);
  go("move", "forward", 72, 127);
  go("claw", "open", false, 127);
  go("turn", "counterclockwise", 180, 127);
  go("move", "backward", 100, 127);
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    motor[frontRight] = vexRT[Ch2]; 											// forward or backward motion
		motor[backRight] = vexRT[Ch2];
		motor[frontLeft] = vexRT[Ch3];
		motor[backLeft] = vexRT[Ch3];
		/*----------------------------------------------------------------------------------------------*/
  	if (vexRT[Btn6UXmtr2] == 1)														// Arm moves up
		{
			motor[armRight] = 127;
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
		}
		else if (vexRT[Btn6DXmtr2] == 1)					   					// Arm moves down
		{
			motor[armRight] = -127;
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
		}
		else																									// Arm stays still
		{
			motor[armRight] = 0;
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
		}
  	/*---------------------------------------------------------------------------------------------*/
  	if (vexRT[Btn8UXmtr2] == 1)														// Cone Joint Up
		{
			motor[clawJoint] = 127;
		}
		else if (vexRT[Btn8DXmtr2] == 1)											// Cone Joint Down
		{
			motor[clawJoint] = -127;
		}
		else																									// Stays still
		{
			motor[clawJoint] = 0;
		}
		/*---------------------------------------------------------------------------------------------*/
		if (vexRT[Btn5UXmtr2] == 1)														// Mobile goal lift rises
		{
			motor[mobileRight] = 127;
			motor[mobileLeft] = 127;
		}
		else if (vexRT[Btn5DXmtr2] == 1)											// Mobile goal lift lowers
		{
			motor[mobileRight] = -127;
			motor[mobileLeft] = -127;
		}
		else																						      // Mobile goal lift stays still
		{
			motor[mobileRight] = 0;
			motor[mobileLeft] = 0;
		}
    UserControlCodePlaceholderForTesting();
  }
}
